### ISSUE TITLE
ChessBoard has no chess pieces displayed

### ISSUE THREAD

**Issue by xingfanxia** [tutsplus/get-started-with-meteor#1]
Hi Andrew,
    I am learning the tutorial and I got stuck. So I decided to download this demo to find out what's wrong. However, when I deploy it to localhost, the chessboard has no chess pieces displayed.

**Comment by andrew8088** [comment]
That's strange; it works fine for me. Here are the steps I took:
- `git clone` this repository
- `cd` into the `chess` subdirectory
- run `meteor` to start the server
- the site is now visible at `localhost:3000`
- create two user accounts
- create a game between them
- both users can now take turns. I have a working chess board with pieces that both players can move

If you follow these steps, what do yo see?

**Comment by xingfanxia** [comment]
I tried exactly the same yesterday. And I have tried for once more just now; it is still not showing pieces. Probably some library thing?? Where do those chess pieces images come from?
![http://7xqpdw.com1.z0.glb.clouddn.com/Screen%20Shot%202016-03-17%20at%208.48.06%20AM.png](http://7xqpdw.com1.z0.glb.clouddn.com/Screen%20Shot%202016-03-17%20at%208.48.06%20AM.png)

**Comment by andrew8088** [comment]
They aren't actually images; they're font characters. They come from the `lib/pieces.js` file. Try replacing the contents of that file with this, and let me know if that makes a difference.

```
pieces = {
  K: 'K',
  Q: 'Q',
  R: 'R',
  B: 'B',
  N: 'N',
  P: 'P',

  k: 'k',
  q: 'q',
  r: 'r',
  b: 'b',
  n: 'n',
  p: 'p'
};
```

**Comment by xingfanxia** [comment]
![http://7xqpdw.com1.z0.glb.clouddn.com/Screen%20Shot%202016-03-17%20at%208.57.57%20AM.png](http://7xqpdw.com1.z0.glb.clouddn.com/Screen%20Shot%202016-03-17%20at%208.57.57%20AM.png)
Yeah, the letters showed up

**Comment by andrew8088** [comment]
So, the chess symbols are part of Unicode; to see the symbols, [you need to be using a font with good Unicode support](https://en.wikipedia.org/wiki/Chess_symbols_in_Unicode). If you'd like to see the chess symbols, switch back to the original `lib/pieces.js` file, and try changing the font (either through your browser or through the CSS). Let me know if that works!

**Comment by xingfanxia** [comment]
Got it! Thx! Also in the tutorial your meteor auto compiles when you makes changes and I have to compile manually, why is that?

**Comment by andrew8088** [comment]
Make sure you're using the latest version of Meteor. Then, you should be able to run `meteor` on the terminal, leave it running, and it will automatically rebuild your app when you make changes.

**Comment by xingfanxia** [comment]
Sorry, one more thing. How to make the chess pieces work universally? It works in another desktop but it won't work on my laptop...Also, the chat box is not rendered properly on the desktop while no trouble on the laptop (Specifically: works in Firefox, doesn't work in Safari&Chrome)

**Comment by andrew8088** [comment]
No problem :). The pieces will work if the computer has a font with good Unicode support (and, I guess, if that font is selected via CSS); try playing with `font-family` in the CSS, and see if that improves things.

The chat box should be rendered properly everywhere; after all, we're using Bootstrap to style it. What does it look like?

**Comment by xingfanxia** [comment]
![http://7xqpdw.com1.z0.glb.clouddn.com/Screen%20Shot%202016-03-17%20at%209.18.13%20AM.png](http://7xqpdw.com1.z0.glb.clouddn.com/Screen%20Shot%202016-03-17%20at%209.18.13%20AM.png)
Sorry about the profanity :)

**Comment by andrew8088** [comment]
The messages aren't being styled; make sure you are giving those element the `me` and `them` CSS classes. See `client/chat/chat.html` and the `getClass` helper method in `client/chat/chat.js`.

**Comment by xingfanxia** [comment]
However, it works somewhere else tho..It works in all browsers on my laptop

**Comment by xingfanxia** [comment]
Have tried some Webfonts to resolve the pieces display like 
`* {
    font-family: 'Open Sans', sans-serif;
}`
However still not working on my laptop..Could it be a cookie thing?

**Comment by andrew8088** [comment]
It should work with just Helvetica or Arial. Try adding `<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />` to the `head` element in the `client/templates/index.html` file.
